### PR TITLE
Issue #1527 Add support for physical back button in region and language drawer

### PR DESCRIPTION
**Pull request by brandon-PG**

### CODE REVIEW

**Comment by ian-lin-PG** [comment]
@brandon-PG I just noticed a related bug, the back button when the app first start up will cause a crash. I found out after clicking one extra back button after closing the drawers. This also shows up on staging app. Though it's not specific to this issue, it does touch on similar code, I think it can fixed within this PR.

**Comment by ian-lin-PG** [comment]
here is a screenshot of the showstopper
Screenshot_20210707-141150

**Comment by brandon-PG** [comment]
> @brandon-PG I just noticed a related bug, the back button when the app first start up will cause a crash. I found out after clicking one extra back button after closing the drawers. This also shows up on staging app. Though it's not specific to this issue, it does touch on similar code, I think it can fixed within this PR.

This crash is fixed

**Comment by ian-lin-PG** [comment]
I can confirm pressing the back button at the beginning closes the app instead of crashing the app.

**Review by ian-lin-PG — APPROVED** [review]

**Pull request merged**
