### PR TITLE
Issue #703 Style markdown component

### PR DESCRIPTION
**Pull request by bensinjin**
Along with the styling outlined in #703 these changes will also address some unwanted padding for the "Read more" component, discussed here: https://github.com/pg-irc/pathways-frontend/issues/663. The issues with cut-off text have been thoroughly discussed and come down to platform specific problems that we don't intend on fixing at this moment.

It may be useful if @cherrielam took a look at this PR as I've had to somewhat improvise on the heading style (although it should seem reasonable).

### CODE REVIEW

**Comment by cherrielam** [comment]
As per discussion with @bensinjin earlier, if we can add the same kind of padding to the body (markdown component) of topic detail that would be great. Maybe for the heading we could use Heading H3 style or Heading H5 style? as per: https://zpl.io/bLxdOXM (currently is the heading H1 or H2?)

**Comment by bensinjin** [comment]
Thx @cherrielam, to elaborate (personal note to self): We want add the (think it's 10dpi, there should be a RN "class" for this as it's applied throughout the app) padding to the markdown component.

**Comment by bensinjin** [comment]
@cherrielam's comment has been addressed.

**Comment by bensinjin** [comment]
@rasmus-storjohann-PG there are two conflicts here that I'd like to properly understand. I'm sure we could likely rebase this more accurately/quickly if we did it together, let's coordinate something so nothing important is lost.

**Comment by rasmus-storjohann-PG** [comment]
@bensinjin I'll have a shot at this rebase

**Comment by bensinjin** [comment]
> @bensinjin I'll take a shot at this rebase

Sounds good, I can do a quick review after if you need

**Comment by rasmus-storjohann-PG** [comment]
@bensinjin you're right that the easiest way to resolve this is for the two of us to sit down with it. However, that can't happen this week. The changes you're needing to merge in are related to the views as they appear in Arabic. I'll outline the possible regressions that your change may create and you can double check that it all works:
* Task detail page: In Arabic: Keep a close eye on the "Read more"/"Read less" buttons, making sure the arrow ends up on the correct side of the button.
* Service list page: In Arabic, the page should be all in English and look like the page does in English, including the Read more/Read less. My changes were making sure that the arrow appears on the correct side of the text on the label. In the process I also cleaned up the code a bit which made for difficult merge conflicts. That's a risk with cleanup.
So can you just make sure that your PR doesn't break these things and then rebase selecting your changes over mine throughout?

**Comment by rasmus-storjohann-PG** [comment]
This business I needed to do
```
const button = this.flipLeftRightOrientation() ?
            <Button onPress={onPress} transparent iconLeft >
                {buttonIcon}
                {buttonText}
            </Button> :
            <Button onPress={onPress} transparent iconRight >
                {buttonText}
                {buttonIcon}
            </Button>;
```
was all for getting the icon on the correct side of the button.

**Comment by rasmus-storjohann-PG** [comment]
This change
```ts
    const label = <Text style={[textStyles.paragraphBoldBlackLeft, textStyles.alwaysLeftAlign]}>Web: </Text>;
    const link = <AnalyticsLink href={website} currentPath={currentPath} linkContext={linkContext}
        linkType={'Website'} style={textStyles.paragraphStyle}>{website}</AnalyticsLink>;

    return <Text>{label}{link}</Text>;

```
is just about making the code more readable. The long blocks of more than 5 lines of JSX always breaks the single responsibility principle. You don't need to make these changes, but I would be glad to see you shift your JSX coding style towards smaller blocks of markdown.

**Comment by bensinjin** [comment]
@rasmus-storjohann-PG I've completed the rebase and kept in mind your comments, please take a final look.

We sort of have two problems: code style and how to apply SRP to component construction.

Code style is easily addressed with tools like [Prettier](https://prettier.io/), this has worked great on other projects and I'd be happy to get it brought into Arrival Advisor

In regards to SRP when it comes to JSX... I know this has been an ongoing discussion ...

Can we clearly define when a component breaks SRP? On another note, saying a component should only be N number of lines just makes people write longer lines (from what I can tell). I mean technically as you say JSX is always breaking SRP. Also, in React, the major point we would have for splitting up a component is to reuse it elsewhere - I personally have found this to be a much better guide than SRP (within reason, I also don't like huge walls of JSX). I personally think we already have too many "sub" components and that the reason this conversation keeps happening is the fact that SRP doesn't nicely apply to an HTML like structure.

Regardless of my thoughts, I can try and make my component more small and focused.

**Comment by rasmus-storjohann-PG** [comment]
Yeah, @bensinjin  I realize that we have had this discussion before. Here's an example of where there is real value to breaking up the JSX:
```ts
const button = this.flipLeftRightOrientation() ?
            <Button onPress={onPress} transparent iconLeft >
                {buttonIcon}
                {buttonText}
            </Button> :
            <Button onPress={onPress} transparent iconRight >
                {buttonText}
                {buttonIcon}
            </Button>;
```
Here there is some logic to return two variants of a button depending on the situation. This code is written so that the things that are different in the two variants is as clear as I could make it. This was accomplished by removing everything that is NOT different out into other local variables of JSX.

**Comment by rasmus-storjohann-PG** [comment]
In this example
```ts
    const label = <Text style={[textStyles.paragraphBoldBlackLeft, textStyles.alwaysLeftAlign]}>Web: </Text>;
    const link = <AnalyticsLink href={website} currentPath={currentPath} linkContext={linkContext}
        linkType={'Website'} style={textStyles.paragraphStyle}>{website}</AnalyticsLink>;

    return <Text>{label}{link}</Text>;
```
the benefit is to tell the reader that this code makes a text element that contains a label and a link. If it was one big JSX block, then the reader woulld need to parse a lot of JSX, making sure that the white space lines things up correctly so that (s)he parses it correctly, etc, and then interpret each part of the JSX to figure out that it is a label and a link. That is a lot more work.

**Comment by bensinjin** [comment]
Your first point I entirely agree with and make a point of doing myself (let me know when I miss it).

To your second point, this:
```
const label = <Text style={[textStyles.paragraphBoldBlackLeft, textStyles.alwaysLeftAlign]}>Web: </Text>;
const link = <AnalyticsLink href={website} currentPath={currentPath} linkContext={linkContext} linkType={'Website'} style={textStyles.paragraphStyle}>{website}</AnalyticsLink>;
```
I would much sooner write over multiple lines like:
```
... ("label" one is probably fine on one line)
const link = (
    <AnalyticsLink
        href={website}
        currentPath={currentPath}
        linkContext={linkContext}
        linkType={'Website'}
        style={textStyles.paragraphStyle}
    >
            {website}
    </AnalyticsLink>
);
```
And I don't think that should be "not allowed" because it's more than 5 lines. Maybe you could say no more than N nested components per component but 5 lines doesn't seem like the right rule to be making.

**Comment by rasmus-storjohann-PG** [comment]
Did a QA pass on this, looking for regressions in the left/right alignment in Arabic. Looks good.

**Pull request merged**
