### PR TITLE
Update jsLingui to latest release (#99)

### PR DESCRIPTION
**Pull request by tnightingale**
Updates to jsLingui 2.1.0 (which resolves the Babel dependency issue).

### CODE REVIEW

**Comment by rasmus-storjohann-PG** [comment]
@tnightingale did you QA this?

**Comment by tnightingale** [comment]
I QA'd `yarn install`, `yarn extract-strings` and `yarn build-strings`. I see there's still an issue with with building during `yarn start`. Sorry, stand-by

**Comment by tnightingale** [comment]
Clearing `node_modules` and rerunning `yarn install` inexplicably fixes the build problem.

In these cases I haven't found way to get a better description of what went wrong beyond "The package failed  to build" if anyone has any insights I'd love to hear them.

**Comment by tnightingale** [comment]
Come to think of it, It's likely that running `yarn clean` also resolves the build problem (without needing to nuke and rebuild `node_modules`).

**Pull request merged**
