### PR TITLE
WIP Issue #548 get location never returns on some androids

### PR DESCRIPTION
**Pull request by tomy-pg**

### CODE REVIEW

**Comment by tomy-pg** [comment]
Updated to expo 32.0.6. This version should have introduced this fix: https://github.com/expo/expo/pull/3273 which could be helpful for solving this problem.

**Comment by bensinjin** [comment]
@tomy-pg have you demonstrated that the changes in master do indeed fix the bug?

**Comment by tomy-pg** [comment]
@bensinjin This PR is a WIP at the moment. I still need to work on this and test the changes.

**Comment by tomy-pg** [comment]
Discussions relating to the location problem - https://github.com/expo/expo/issues/946
Some notes I have taken down - https://docs.google.com/document/d/1emsj507egcqQrHfAA-i4lf_f0Vk_tf7zZ1jwkaFZBGA/edit

**Comment by bensinjin** [comment]
Closing this as it has been addressed in this PR: https://github.com/pg-irc/pathways-frontend/pull/580

**Pull request closed without merging**
