### PR TITLE
Feature/issue 1505 update questionnaire for two regions

### PR DESCRIPTION
**Pull request by rasmus-storjohann-PG**

### CODE REVIEW

**Review by brandon-PG — APPROVED** [review]
Works as intended

**Comment by alysha-PG** [comment]
Updates needed to MB questionnaire.

- Q. 6. housing (NOTE: please change to both **MB and BC**):

- [ ] answers should read (in this order)-
1.  I want to rent a place to live
2. I already rent a place to live
3. I want to buy a home
4. I already own a home
Image from iOS (4)


- Q. 7. current level of English:
- [ ] Remove Canadian Language Benchmark mention and levels
Image from iOS (2)


- Q. 10 work
- [ ] add "Select all that apply"
- [ ] remove "None of the above"
Image from iOS (3)

**Comment by alysha-PG** [comment]
@rasmus-storjohann-PG questionnaire should read exactly as is in the first tab here:
https://docs.google.com/spreadsheets/d/1gn4KH_qlVcosFIDiYENVw4uGMWpcvrJwy4zU9gMpPXE/edit?usp=sharing

**Specific changes to make:**
Q. 3. When I go to the questionnaire, expected behavior is there is a Q3. Instead now, it skips from Q2 to Q4. This question is expected to be the one about current immigration status, instead nothing is there and that question is currently Q9.

- [ ] make Q3 immigration status Q

Q. 6. housing (NOTE: please change to both MB and BC):

- [ ] Change order of questions and content. Answers should read (in this order)-

    I want to rent a place to live
    I already rent a place to live
    I want to buy a home
    I already own a home

Q. 7. current level of English:
- [ ] Remove Canadian Language Benchmark mention and levels. Should only read None, Beginner, Intermediate, Fluent.

Q. 10 work

- [ ] add "Select all that apply"
- [ ] remove "None of the above"

Q. 11 Health care

- [ ] Remove BC-specific "Prescription medication" and "Eye doctors"

**Comment by alysha-PG** [comment]
@deniza-pg

**Comment by rasmus-storjohann-PG** [comment]
Issues listed above are fixed as part of #1505

**Pull request merged**
